# Generated by Django 4.2.7 on 2023-12-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiverPlate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuotaMensual',
        ),
        migrations.DeleteModel(
            name='GrupoFamiliar',
        ),
    ]
